# Generated by Django 3.2.25 on 2024-05-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20240527_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubconfiguration',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'ordering': ('id',)},
        ),
    ]
