# Generated by Django 3.2.25 on 2024-05-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_project_edge_v2_migration_read_capacity_budget'),
        ('tags', '0005_add_tag_fields_for_stale_flags_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('NONE', 'None'), ('STALE', 'Stale'), ('GITHUB', 'Github')], default='NONE', help_text='Field used to provide a consistent identifier for the FE and API to use for business logic.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('project', 'type', 'label')},
        ),
    ]
